conda-forge/xtensor-feedstock

.gitattributes
README.md
appveyor.yml

Closes https://github.com/conda-forge/xtensor-feedstock/pull/8

MNT: Re-rendered with conda-smithy 1.7.0 [ci skip]

---

recipe/bld.bat
recipe/build.sh
recipe/meta.yaml
recipe/run_test.bat
recipe/run_test.sh

As per https://github.com/conda-forge/staged-recipes/issues/2168

Use cmake install instead of copying headers

---

.travis.yml
LICENSE
appveyor.yml
ci_support/run_docker_build.sh
recipe/meta.yaml

Also re-rendered the feedstock.

Release 0.4.0

---

recipe/meta.yaml

Hopefully, that should also be the first version on Debian too.

Release 0.8.2

---

recipe/meta.yaml

Release 0.16.3

---

recipe/meta.yaml

Release 0.16.4

---

recipe/meta.yaml

Separate host dependencies

---

recipe/meta.yaml

release 0.17.1

---

recipe/meta.yaml

release 0.17.2

---

recipe/meta.yaml

Release 0.17.3

---

recipe/meta.yaml

Release 0.18.2

---

.appveyor.yml
.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-osx.yml
.azure-pipelines/azure-pipelines-win.yml
.azure-pipelines/build_steps.sh
.azure-pipelines/run_docker_build.sh
.travis.yml
README.md
azure-pipelines.yml
recipe/meta.yaml

Release 0.19.1

---

recipe/meta.yaml

Release 0.20.3

---

.azure-pipelines/run_docker_build.sh
README.md
recipe/meta.yaml

Release 0.20.5

---

recipe/meta.yaml

Release 0.21.2

---

recipe/meta.yaml

Release 0.21.10

---

recipe/meta.yaml

Release 0.23.1

---

recipe/meta.yaml

Release 0.23.3

---

recipe/meta.yaml

Release 0.23.4

---

recipe/meta.yaml

Release 0.23.5

---

recipe/meta.yaml

Release 0.23.7

---

recipe/meta.yaml

Release 0.23.9

---

recipe/meta.yaml

Added xsimd in run_constrained section

---

recipe/meta.yaml

Release 0.23.10

---

recipe/meta.yaml

Release 0.24.3

---

recipe/meta.yaml

Relaxed run constraints on xsimd

---

.azure-pipelines/azure-pipelines-linux.yml
.azure-pipelines/azure-pipelines-win.yml
.ci_support/linux_64_.yaml
.ci_support/linux_aarch64_.yaml
.ci_support/linux_ppc64le_.yaml
.ci_support/osx_64_.yaml
.ci_support/osx_arm64_.yaml
.scripts/run_osx_build.sh
recipe/meta.yaml

Release 0.24.7
